from __future__ import annotations

import json
import math
from datetime import date, timedelta

from backend.app.config import (
    COMMODITIES_SEED_PATH,
    DEFAULT_GENERATED_AT,
    REFRESH_LOG_PATH,
    RUNTIME_DIR,
    RUNTIME_SIGNALS_PATH,
    SCENARIOS_SEED_PATH,
    SIGNALS_SEED_PATH,
)


def build_proxy_series(start: date, base: float, drift: float, amplitude: float) -> list[dict[str, object]]:
    series = []
    for index in range(16):
        current = start + timedelta(days=7 * index)
        value = base + (index * drift) + math.sin(index / 2.5) * amplitude
        series.append({"date": current.isoformat(), "value": round(value, 2)})
    return series


def build_seed_commodities() -> dict[str, object]:
    start = date(2026, 2, 1)

    commodities = [
        {
            "id": "aluminium",
            "region": "Europe",
            "proxy_label": "Market pressure index",
            "proxy_value_label": "Composite pressure index",
            "proxy_score": 73,
            "volatility_index": 16,
            "proxy_series": build_proxy_series(start, 66, 0.9, 3.2),
            "previous_snapshot": {"risk_score": 68, "recommended_action": "monitor"},
        },
        {
            "id": "pet",
            "region": "Europe",
            "proxy_label": "Polymer cost proxy",
            "proxy_value_label": "Polymer proxy index",
            "proxy_score": 58,
            "volatility_index": 11,
            "proxy_series": build_proxy_series(start, 52, 0.25, 2.1),
            "previous_snapshot": {"risk_score": 45, "recommended_action": "wait"},
        },
        {
            "id": "energy",
            "region": "Europe",
            "proxy_label": "Power and gas pressure index",
            "proxy_value_label": "Energy pressure index",
            "proxy_score": 76,
            "volatility_index": 18,
            "proxy_series": build_proxy_series(start, 63, 0.95, 4.1),
            "previous_snapshot": {"risk_score": 71, "recommended_action": "hedge"},
        },
        {
            "id": "barley",
            "region": "Iberia",
            "proxy_label": "Agricultural pressure index",
            "proxy_value_label": "Agricultural pressure index",
            "proxy_score": 54,
            "volatility_index": 12,
            "proxy_series": build_proxy_series(start, 49, 0.35, 2.8),
            "previous_snapshot": {"risk_score": 52, "recommended_action": "monitor"},
        },
    ]
    return {
        "generated_at": DEFAULT_GENERATED_AT,
        "commodities": commodities,
    }


def build_seed_signals() -> dict[str, object]:
    signals = [
        {
            "id": "alu-energy-01",
            "commodity": "aluminium",
            "driver": "energy",
            "event": "European power costs remain elevated ahead of summer contracts",
            "date": "2026-05-22",
            "region": "Europe",
            "direction": "bullish",
            "impact_score": 0.82,
            "confidence": 0.78,
            "horizon": "1-3 months",
            "source_name": "Cala / Energy Monitor",
            "source_url": "https://cala.ai/example/aluminium-energy",
            "evidence": "Utilities and smelter cost curves are still pricing expensive electricity into near-term output.",
            "mechanism": "Higher smelter energy costs push aluminium conversion and procurement costs upward.",
            "used_in_score": True,
        },
        {
            "id": "alu-inv-02",
            "commodity": "aluminium",
            "driver": "inventories",
            "event": "Warehouse drawdowns tighten nearby spot availability",
            "date": "2026-05-21",
            "region": "Europe",
            "direction": "bullish",
            "impact_score": 0.74,
            "confidence": 0.73,
            "horizon": "2-6 weeks",
            "source_name": "Cala / Metals Storage",
            "source_url": "https://cala.ai/example/aluminium-inventories",
            "evidence": "Inventory coverage continues to shrink versus the last rolling quarter.",
            "mechanism": "Lower stocks reduce supply flexibility and increase the risk of upside pricing.",
            "used_in_score": True,
        },
        {
            "id": "alu-supply-03",
            "commodity": "aluminium",
            "driver": "supply",
            "event": "Maintenance outages limit primary metal availability",
            "date": "2026-05-20",
            "region": "Europe",
            "direction": "bullish",
            "impact_score": 0.69,
            "confidence": 0.71,
            "horizon": "1 month",
            "source_name": "Cala / Supply Bulletin",
            "source_url": "https://cala.ai/example/aluminium-supply",
            "evidence": "Multiple regional plants are running below plan during maintenance windows.",
            "mechanism": "Temporary outages lower prompt supply and increase buyer urgency.",
            "used_in_score": True,
        },
        {
            "id": "alu-demand-04",
            "commodity": "aluminium",
            "driver": "demand",
            "event": "Industrial demand remains softer in selected end markets",
            "date": "2026-05-18",
            "region": "Europe",
            "direction": "bearish",
            "impact_score": 0.52,
            "confidence": 0.63,
            "horizon": "1-2 months",
            "source_name": "Cala / Manufacturing Pulse",
            "source_url": "https://cala.ai/example/aluminium-demand",
            "evidence": "Automotive and construction order books are uneven across the region.",
            "mechanism": "Softer downstream demand offsets part of the supply-side inflation risk.",
            "used_in_score": True,
        },
        {
            "id": "alu-imports-05",
            "commodity": "aluminium",
            "driver": "imports_exports",
            "event": "Higher import availability eases part of the pressure",
            "date": "2026-05-17",
            "region": "EMEA",
            "direction": "bearish",
            "impact_score": 0.47,
            "confidence": 0.58,
            "horizon": "1 month",
            "source_name": "Cala / Trade Lens",
            "source_url": "https://cala.ai/example/aluminium-trade",
            "evidence": "Incoming tonnage partially offsets regional shortages.",
            "mechanism": "Imported material improves optionality and caps spot spikes.",
            "used_in_score": True,
        },
        {
            "id": "pet-oil-01",
            "commodity": "pet",
            "driver": "oil",
            "event": "Crude remains range-bound with mild upside bias",
            "date": "2026-05-22",
            "region": "Global",
            "direction": "bullish",
            "impact_score": 0.61,
            "confidence": 0.67,
            "horizon": "2-4 weeks",
            "source_name": "Cala / Energy Feedstocks",
            "source_url": "https://cala.ai/example/pet-oil",
            "evidence": "Oil markets have not broken out, but the floor is firmer than last month.",
            "mechanism": "Oil resilience supports PET cost expectations through upstream feedstocks.",
            "used_in_score": True,
        },
        {
            "id": "pet-pta-02",
            "commodity": "pet",
            "driver": "PTA_MEG",
            "event": "PTA spreads are edging higher",
            "date": "2026-05-21",
            "region": "Global",
            "direction": "bullish",
            "impact_score": 0.64,
            "confidence": 0.69,
            "horizon": "1 month",
            "source_name": "Cala / Polymers Feedstock",
            "source_url": "https://cala.ai/example/pet-pta",
            "evidence": "Feedstock spreads widened during the latest trading sessions.",
            "mechanism": "Higher PTA and MEG costs pass through into polymer pricing pressure.",
            "used_in_score": True,
        },
        {
            "id": "pet-reg-03",
            "commodity": "pet",
            "driver": "regulation",
            "event": "Recycled content compliance keeps premium grades tight",
            "date": "2026-05-19",
            "region": "Europe",
            "direction": "bullish",
            "impact_score": 0.56,
            "confidence": 0.62,
            "horizon": "1-3 months",
            "source_name": "Cala / Circular Packaging",
            "source_url": "https://cala.ai/example/pet-regulation",
            "evidence": "Compliance timelines continue to favour constrained premium recycled material.",
            "mechanism": "Regulatory pressure supports PET and recycled PET procurement costs.",
            "used_in_score": True,
        },
        {
            "id": "pet-supply-04",
            "commodity": "pet",
            "driver": "supply",
            "event": "Converters report adequate prompt resin coverage",
            "date": "2026-05-18",
            "region": "Europe",
            "direction": "bearish",
            "impact_score": 0.58,
            "confidence": 0.65,
            "horizon": "2-4 weeks",
            "source_name": "Cala / Packaging Supply",
            "source_url": "https://cala.ai/example/pet-supply",
            "evidence": "Short-term supply looks manageable despite structural cost pressure.",
            "mechanism": "Comfortable coverage softens the urgency to buy immediately.",
            "used_in_score": True,
        },
        {
            "id": "pet-imports-05",
            "commodity": "pet",
            "driver": "imports_exports",
            "event": "Imported resin offers provide a lower-cost alternative",
            "date": "2026-05-17",
            "region": "EMEA",
            "direction": "bearish",
            "impact_score": 0.46,
            "confidence": 0.61,
            "horizon": "2-6 weeks",
            "source_name": "Cala / Trade Lens",
            "source_url": "https://cala.ai/example/pet-imports",
            "evidence": "Imported offers create downside resistance for domestic producers.",
            "mechanism": "Trade availability tempers local price escalation.",
            "used_in_score": True,
        },
        {
            "id": "ene-geo-01",
            "commodity": "energy",
            "driver": "geopolitics",
            "event": "Gas market remains sensitive to geopolitical disruptions",
            "date": "2026-05-22",
            "region": "Europe",
            "direction": "bullish",
            "impact_score": 0.79,
            "confidence": 0.76,
            "horizon": "1-3 months",
            "source_name": "Cala / Macro Energy",
            "source_url": "https://cala.ai/example/energy-geopolitics",
            "evidence": "Regional gas pricing still carries a premium for disruption risk.",
            "mechanism": "Geopolitical stress lifts forward energy costs for industrial buyers.",
            "used_in_score": True,
        },
        {
            "id": "ene-weather-02",
            "commodity": "energy",
            "driver": "weather",
            "event": "Warm weather outlook increases volatility for power demand",
            "date": "2026-05-21",
            "region": "Europe",
            "direction": "bullish",
            "impact_score": 0.66,
            "confidence": 0.72,
            "horizon": "2-4 weeks",
            "source_name": "Cala / Weather Risk",
            "source_url": "https://cala.ai/example/energy-weather",
            "evidence": "Weather models show conditions that can strain balancing costs.",
            "mechanism": "Demand spikes and grid balancing costs feed into procurement risk.",
            "used_in_score": True,
        },
        {
            "id": "ene-futures-03",
            "commodity": "energy",
            "driver": "futures_prices",
            "event": "Near-term power contracts keep a firm tone",
            "date": "2026-05-20",
            "region": "Europe",
            "direction": "bullish",
            "impact_score": 0.71,
            "confidence": 0.74,
            "horizon": "1 month",
            "source_name": "Cala / Forward Curves",
            "source_url": "https://cala.ai/example/energy-futures",
            "evidence": "The front of the curve is still trading above the recent average.",
            "mechanism": "A firmer curve increases the cost of waiting for prompt coverage.",
            "used_in_score": True,
        },
        {
            "id": "ene-demand-04",
            "commodity": "energy",
            "driver": "demand",
            "event": "Industrial demand remains softer than seasonal norms",
            "date": "2026-05-18",
            "region": "Europe",
            "direction": "bearish",
            "impact_score": 0.53,
            "confidence": 0.64,
            "horizon": "1 month",
            "source_name": "Cala / Industrial Pulse",
            "source_url": "https://cala.ai/example/energy-demand",
            "evidence": "Some downstream consumers are still below expected run-rates.",
            "mechanism": "Softer industrial demand offsets part of the upside energy risk.",
            "used_in_score": True,
        },
        {
            "id": "ene-supply-05",
            "commodity": "energy",
            "driver": "supply",
            "event": "Maintenance windows reduce flexibility in regional generation",
            "date": "2026-05-17",
            "region": "Europe",
            "direction": "bullish",
            "impact_score": 0.62,
            "confidence": 0.68,
            "horizon": "2-6 weeks",
            "source_name": "Cala / Power Supply",
            "source_url": "https://cala.ai/example/energy-supply",
            "evidence": "Maintenance schedules reduce spare capacity in the near term.",
            "mechanism": "Lower system flexibility amplifies the impact of adverse weather or outages.",
            "used_in_score": True,
        },
        {
            "id": "bar-weather-01",
            "commodity": "barley",
            "driver": "weather",
            "event": "Dry conditions are increasing crop stress in key areas",
            "date": "2026-05-22",
            "region": "Iberia",
            "direction": "bullish",
            "impact_score": 0.67,
            "confidence": 0.71,
            "horizon": "1-3 months",
            "source_name": "Cala / Weather Risk",
            "source_url": "https://cala.ai/example/barley-weather",
            "evidence": "Persistent dryness raises concern about yield variability.",
            "mechanism": "Weather stress reduces supply confidence and can push barley procurement costs up.",
            "used_in_score": True,
        },
        {
            "id": "bar-supply-02",
            "commodity": "barley",
            "driver": "supply",
            "event": "Crop availability remains uneven across producing regions",
            "date": "2026-05-21",
            "region": "Europe",
            "direction": "bullish",
            "impact_score": 0.58,
            "confidence": 0.69,
            "horizon": "1-2 months",
            "source_name": "Cala / Agri Supply",
            "source_url": "https://cala.ai/example/barley-supply",
            "evidence": "Regional supply signals remain mixed with downside harvest risk.",
            "mechanism": "Supply uncertainty raises the risk of needing to cover earlier.",
            "used_in_score": True,
        },
        {
            "id": "bar-trade-03",
            "commodity": "barley",
            "driver": "imports_exports",
            "event": "Trade flows are offering some balancing volume",
            "date": "2026-05-19",
            "region": "Europe",
            "direction": "bearish",
            "impact_score": 0.51,
            "confidence": 0.62,
            "horizon": "2-4 weeks",
            "source_name": "Cala / Trade Lens",
            "source_url": "https://cala.ai/example/barley-trade",
            "evidence": "Import alternatives provide some relief for prompt physical coverage.",
            "mechanism": "Trade availability offsets part of the crop stress premium.",
            "used_in_score": True,
        },
        {
            "id": "bar-demand-04",
            "commodity": "barley",
            "driver": "demand",
            "event": "Feed demand is stable rather than accelerating",
            "date": "2026-05-18",
            "region": "Europe",
            "direction": "bearish",
            "impact_score": 0.44,
            "confidence": 0.57,
            "horizon": "1 month",
            "source_name": "Cala / Agri Demand",
            "source_url": "https://cala.ai/example/barley-demand",
            "evidence": "Downstream demand is steady, reducing the urgency of a sharp buy-up.",
            "mechanism": "Stable demand limits upside urgency if supply risks do not worsen.",
            "used_in_score": True,
        },
        {
            "id": "bar-inv-05",
            "commodity": "barley",
            "driver": "inventories",
            "event": "Buyer inventories remain workable but not comfortable",
            "date": "2026-05-17",
            "region": "Iberia",
            "direction": "bullish",
            "impact_score": 0.49,
            "confidence": 0.61,
            "horizon": "2-6 weeks",
            "source_name": "Cala / Inventory Monitor",
            "source_url": "https://cala.ai/example/barley-inventories",
            "evidence": "Coverage exists, but buffers are not wide if weather risk intensifies.",
            "mechanism": "Limited inventory buffers reduce flexibility in a tightening crop scenario.",
            "used_in_score": True,
        },
    ]
    return {
        "generated_at": DEFAULT_GENERATED_AT,
        "refresh_status": "seed",
        "signals": signals,
    }


def build_scenarios_catalog() -> dict[str, object]:
    return {
        "generated_at": DEFAULT_GENERATED_AT,
        "variables": [
            {
                "id": "energy_cost_shock",
                "label": "Energy cost shock (%)",
                "type": "range",
                "min": -20,
                "max": 30,
                "step": 5,
                "default": 0,
                "applies_to": ["aluminium", "pet", "energy", "barley"],
            },
            {
                "id": "oil_shock",
                "label": "Oil shock (%)",
                "type": "range",
                "min": -20,
                "max": 30,
                "step": 5,
                "default": 0,
                "applies_to": ["pet", "energy"],
            },
            {
                "id": "supply_disruption",
                "label": "Supply disruption",
                "type": "select",
                "default": "none",
                "options": ["none", "mild", "severe"],
                "applies_to": ["aluminium", "pet", "energy", "barley"],
            },
            {
                "id": "demand_outlook",
                "label": "Demand outlook",
                "type": "select",
                "default": "neutral",
                "options": ["weak", "neutral", "strong"],
                "applies_to": ["aluminium", "pet", "energy", "barley"],
            },
            {
                "id": "inventory_level",
                "label": "Inventory level",
                "type": "select",
                "default": "normal",
                "options": ["low", "normal", "high"],
                "applies_to": ["aluminium", "pet", "energy", "barley"],
            },
            {
                "id": "geopolitical_risk",
                "label": "Geopolitical risk",
                "type": "select",
                "default": "medium",
                "options": ["low", "medium", "high"],
                "applies_to": ["aluminium", "pet", "energy", "barley"],
            },
            {
                "id": "weather_risk",
                "label": "Weather risk",
                "type": "select",
                "default": "medium",
                "options": ["low", "medium", "high"],
                "applies_to": ["energy", "barley"],
            },
            {
                "id": "coverage_secured",
                "label": "Coverage already secured (%)",
                "type": "select",
                "default": "0",
                "options": ["0", "25", "50", "75"],
                "applies_to": ["aluminium", "pet", "energy", "barley"],
            },
        ],
    }


def write_json(path, payload: dict[str, object]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as handle:
        json.dump(payload, handle, indent=2)


def main() -> None:
    write_json(COMMODITIES_SEED_PATH, build_seed_commodities())
    write_json(SIGNALS_SEED_PATH, build_seed_signals())
    write_json(SCENARIOS_SEED_PATH, build_scenarios_catalog())
    if RUNTIME_SIGNALS_PATH.exists():
        RUNTIME_SIGNALS_PATH.unlink()
    RUNTIME_DIR.mkdir(parents=True, exist_ok=True)
    write_json(REFRESH_LOG_PATH, {"entries": []})
    print("Seed data rebuilt.")


if __name__ == "__main__":
    main()
